### ISSUE TITLE
[JHipster new module][Error] needs a .yo-rc.json configuration file made by JHipster

### ISSUE THREAD

**Issue by dinukadesilva** [jhipster/generator-jhipster-module#13]
I created a new JHipster module. And when I try to create a project using that module I'm getting this error.

`needs a .yo-rc.json configuration file made by JHipster.`

http://stackoverflow.com/questions/40542862/jhipster-new-moduleerror-needs-a-yo-rc-json-configuration-file-made-by-jhip

**Comment by dinukadesilva** [comment]
Actually I posted the question in Stackoverflow first and then only I posted it here

**Comment by dinukadesilva** [comment]
Highly appreciated if any of you could help on this...

**Comment by jdubois** [comment]
Yes, that's why it's cross posted.
Then it means we'll get it twice, so probably 2 of us will spend time on the same question.
And people looking for answers will have 2 different answers.
Anyway it doesn't seem like a JHipster bug, and this is not following the guidelines: I'm closing this, in favor of Stackoverflow.
