### ISSUE TITLE
GitHub Actions: Generate project - No such file or directory

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/generator-jhipster-module#55]
Steps to reproduce:

1. `yo jhipster-module` to create a new module with the updated version of the generator
2. Push some code into the new module
3. Check the build in GitHub

```
Generate project
0s
##[error]No such file or directory
Run jhipster --with-entities --no-insight
##[error]No such file or directory
```

**Comment by murdos** [comment]
FYI I encountered the same issue while working on a new module.
With this change https://github.com/hipster-labs/generator-jhipster-jqassistant/commit/0f038c1b3ff9e96c432720908a2d0918b66224ff  I then got another error that I've not investigated yet.

**Comment by fdelbrayelle** [comment]
I think in your case it's a different issue?

It's strange because before to execute the `jhipster` command it seems all the mandatory steps are gathered.

**Comment by fdelbrayelle** [comment]
Here is an example of failed build: https://github.com/fdelbrayelle/generator-jhipster-kafka/runs/362460030

**Comment by murdos** [comment]
No, it's the same issue. In fact there are multiple issues, and when you fix the first, you discover the second one:
- the `jhipster` command is executed in a working directory that does not exist since the matrix references non existing directories: https://github.com/jhipster/generator-jhipster-module/blob/bc722194aa601b2aefe39dffa76dc706d6bd584b/generators/app/templates/.github/workflows/github-ci.yml.ejs#L43
- then the `yo jhipster-<module>` never finishes since a prompt happens and is never answered

I'll fix theses issues in the generator.
For your module, you can remove the prompt and change the matrix input as I've done in https://github.com/hipster-labs/generator-jhipster-jqassistant/commit/0f038c1b3ff9e96c432720908a2d0918b66224ff and go forward
